#!/usr/bin/env bash
# Diff C++ schedules against the Python wg_graphs reference, node for node.
#
# Two suites:
#   runtime       the integer-timestep runtimes; every line names each node and
#                 the timestep it was dispatched in
#   cost_runtime  the continuous-time runtimes; every line names each node's
#                 start, duration and lane to six decimal places
#
# The continuous-time dumper prices nodes with the library's own roofline arm,
# so that suite validates the shipped cost model against the reference's cost.py
# rather than a copy of it. Both build without HIP, CMake or Catch2. Comparing whole dumps rather than
# transcribing expectations by hand means a single node moving is caught, and the
# failure is a readable diff rather than one assertion.
#
# Differences are expected only where expected_diff_<suite>.txt records them. At
# the time of writing that is five depth-first lines: the reference orders
# depth-first successors by operation *name* where it means operator order, and
# the port does not reproduce that. See the note on depth_first_rank in
# runtime.hpp. The continuous-time suite is expected to agree exactly.
#
# XcdRuntime lives only on the wg-graphs-figures-update branch, so PYTHONPATH
# must point at a checkout of it:
#   git -C <wg_graphs> worktree add ../wg_graphs_figures wg-graphs-figures-update
#   PYTHONPATH=<...>/wg_graphs_figures tests/graphs/oracle/compare.sh
# Refresh the recorded differences after a deliberate change:
#   PYTHONPATH=... tests/graphs/oracle/compare.sh --record
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../../.." && pwd)"
out="${TMPDIR:-/tmp}/origami-graphs-oracle"
mkdir -p "$out/stub/origami"

# origami_export.h is generated by CMake; the macros are visibility attributes
# with no bearing on the numbers, so a stub is enough to build without it.
cat > "$out/stub/origami/origami_export.h" <<'STUB'
#ifndef ORIGAMI_EXPORT_H
#define ORIGAMI_EXPORT_H
#define ORIGAMI_EXPORT
#define ORIGAMI_NO_EXPORT
#define ORIGAMI_DEPRECATED
#define ORIGAMI_DEPRECATED_EXPORT
#define ORIGAMI_DEPRECATED_NO_EXPORT
#endif
STUB

: "${PYTHONPATH:?set PYTHONPATH to a checkout containing the wg_graphs package}"

record=0
[ "${1:-}" = "--record" ] && record=1
status=0

# Every graphs source except the GEMM bridge, which needs HIP and plays no part
# in either schedule dump.
mapfile -t graph_sources < <(
    find "$root/src/origami/graphs" -name '*.cpp' ! -name 'cost_gemm.cpp' | sort)

for suite in runtime cost_runtime; do
    g++ -std=c++17 -O2 -Wall -Wextra -Wpedantic -Werror \
        -I "$root/include" -I "$out/stub" \
        "${graph_sources[@]}" \
        "$root"/src/origami/comm/latency.cpp \
        "$root"/src/origami/comm/primitives.cpp \
        "$root"/src/origami/types.cpp \
        "$here/${suite}_dump.cpp" \
        -o "$out/${suite}_dump" || exit 1

    "$out/${suite}_dump" > "$out/$suite.cpp.txt" || exit 1
    # Run from elsewhere so the reference resolves through PYTHONPATH rather
    # than through a package that happens to sit next to the script.
    (cd "$out" && python3 "$here/${suite}_oracle.py") > "$out/$suite.py.txt" || exit 1

    # Fixed labels rather than the default filename-and-mtime header, which
    # would otherwise differ on every run and swamp the real comparison.
    diff -u -L reference -L port "$out/$suite.py.txt" "$out/$suite.cpp.txt" \
        > "$out/$suite.diff.txt"

    expected="$here/expected_diff_$suite.txt"
    if [ "$record" = 1 ]; then
        cp "$out/$suite.diff.txt" "$expected"
        echo "$suite: recorded $(grep -c '^+[^+]' "$expected") differing line(s)"
        continue
    fi

    total=$(grep -c . "$out/$suite.cpp.txt")
    # grep exits non-zero on no matches, which is the common case here, so read
    # the count rather than the exit status.
    known=$(grep -c '^+[^+]' "$expected" 2>/dev/null); known=${known:-0}
    if diff -q "$expected" "$out/$suite.diff.txt" > /dev/null 2>&1; then
        if [ "$known" = 0 ]; then
            echo "$suite: all $total line(s) agree with the reference"
        else
            echo "$suite: $((total - known)) of $total line(s) agree; $known known difference(s)"
        fi
    else
        echo "$suite: UNEXPECTED divergence from the reference"
        diff -u "$expected" "$out/$suite.diff.txt"
        status=1
    fi
done

exit $status
