#!/usr/bin/env bash
# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
#
# Build and run the origami::graphs suite with nothing but a C++17 compiler.
#
# The graphs library is HIP-free: it must build and run with no ROCm toolchain,
# no GPU, and no Catch2. This script keeps that claim falsifiable by compiling
# every graphs source and test directly, so it fails the moment something pulls
# in hip::host or a Catch2 header. CI still builds the same sources through CMake
# against Catch2; this is the narrower, stricter gate.
#
# The cost layer's comm arm calls origami::comm, so this build also needs that
# model's host sources. They are listed explicitly rather than globbed, because
# the list doubles as the statement of what graphs is allowed to depend on:
# hardware_device.cpp is absent because it includes hip_runtime.h, and pulling it
# in here should be a link error rather than a silent HIP dependency.
#
# origami_export.h is generated by CMake, so a stub is written for it. The macros
# are visibility attributes with no bearing on behaviour, and faking them is what
# lets this build run without configuring the project.
#
# Usage: ./run_standalone.sh [output-dir]

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out="${1:-${TMPDIR:-/tmp}/origami-graphs-standalone}"
mkdir -p "$out/stub/origami"

cat > "$out/stub/origami/origami_export.h" <<'STUB'
#ifndef ORIGAMI_EXPORT_H
#define ORIGAMI_EXPORT_H
#define ORIGAMI_EXPORT
#define ORIGAMI_NO_EXPORT
#define ORIGAMI_DEPRECATED
#define ORIGAMI_DEPRECATED_EXPORT
#define ORIGAMI_DEPRECATED_NO_EXPORT
#endif
STUB

# cost_gemm is the one HIP-linked piece, so it and its suite are excluded here
# and built by CMake against roc::origami-graphs-gemm instead. Everything else
# has to compile without a ROCm toolchain or this script has stopped proving
# anything.
mapfile -t sources < <(find "$root/src/origami/graphs" -name '*.cpp' ! -name 'cost_gemm.cpp' | sort)
mapfile -t tests < <(find "$root/tests/graphs" -name 'test_*.cpp' ! -name 'test_cost_gemm.cpp' |
                     sort)

# Host-only origami sources the graphs cost layer depends on.
comm_sources=(
    "$root/src/origami/comm/latency.cpp"
    "$root/src/origami/comm/primitives.cpp"
    "$root/src/origami/types.cpp"
)

echo "building ${#sources[@]} graphs source(s), ${#comm_sources[@]} comm source(s)," \
     "${#tests[@]} test file(s)"

g++ -std=c++17 -O2 -Wall -Wextra -Wpedantic -Werror \
    -DORIGAMI_GRAPHS_NO_CATCH2 \
    -I "$root/include" \
    -I "$out/stub" \
    -I "$root/tests/graphs" \
    "${sources[@]}" \
    "${comm_sources[@]}" \
    "${tests[@]}" \
    "$root/tests/graphs/standalone_main.cpp" \
    -o "$out/origami-graphs-tests"

echo
exec "$out/origami-graphs-tests"
